steps:

  - name: 'docker/compose'
    id: 'compose-up'
    args: [
      '-p', 'us-west2-docker.pkg.dev/${PROJECT_ID}/google-cloud-sandbox-repo',
      '-f', 'src/docker-compose.yml',
      'up', '--build', '-d', 'nginx', 'mariadb']

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-f', 'src/legacy_application/Dockerfile',
      '-t', 'us-west2-docker.pkg.dev/${PROJECT_ID}/google-cloud-sandbox-repo/legacy'
    ]

images: [
  'us-west2-docker.pkg.dev/${PROJECT_ID}/google-cloud-sandbox-repo/nginx',
  'us-west2-docker.pkg.dev/${PROJECT_ID}/google-cloud-sandbox-repo/mariadb',
  'us-west2-docker.pkg.dev/${PROJECT_ID}/google-cloud-sandbox-repo/legacy'
  ]

options:
  logging: CLOUD_LOGGING_ONLY