steps:
  # running docker-compose
  - name: 'docker/compose:1.26.2'
    args: ['up', '-d']
    env:
      - 'PROJECT_ID=$PROJECT_ID'
      -
# Build the new docker image.
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcb-docker-compose:latest', '.']

# Push the new image to the registry.
images: ['gcr.io/$PROJECT_ID/gcb-docker-compose:latest']

options:
  logging: CLOUD_LOGGING_ONLY