steps:
# Run docker-compose.yml
  - name: 'docker/compose'
    id: 'compose-up'
    args: [
      '-p', 'us-west2-docker.pkg.dev/${PROJECT_ID}/google-cloud-sandbox-repo'
      '-f', 'src/docker-compose.yml',
      'up', '--build', 'web']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'google-cloud-sandbox-image', 'us-west2-docker.pkg.dev/${PROJECT_ID}/google-cloud-sandbox-repo/google-cloud-sandbox-image']

images: ['us-west2-docker.pkg.dev/$PROJECT_ID/google-cloud-sandbox-repo/google-cloud-sandbox-image']

options:
  logging: CLOUD_LOGGING_ONLY